/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appsistemahospitalar.GUI;

import com.mycompany.appsistemahospitalar.DAO.EspecialidadeDAO;
import com.mycompany.appsistemahospitalar.entities.Especialidade;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nikolas
 */
public class ConsultarEspecialidade extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarEspecialidade
     */
    
    private Connection con;
    private Statement stm;
    private ResultSet res;
    
    public ConsultarEspecialidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBbuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBlistar = new javax.swing.JButton();

        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(this::jBbuscarActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id_especialidade", "nome", "descricao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jBlistar.setText("Listar");
        jBlistar.addActionListener(this::jBlistarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBbuscar)
                    .addComponent(jBlistar))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jBbuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBlistar)
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlistarActionPerformed
        // TODO add your handling code here:
        
         try {
        // Instancia o DAO
        EspecialidadeDAO dao = new EspecialidadeDAO();
        // Chama o método listar (que deve retornar um List<Especialidade>)
        List<Especialidade> lista = dao.listarEspecialidade(); 
        
        // Pega o modelo da tabela
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        // Limpa as linhas atuais da tabela antes de preencher
        model.setNumRows(0); 
        
        // Preenche a tabela com os objetos retornados
        for (Especialidade esp : lista) {
            model.addRow(new Object[]{
                esp.getId_especialidade(), // Ajuste para o nome exato do seu getter
                esp.getNome(),
                esp.getDescricao()
            });
        }
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao listar especialidades: " + e.getMessage());
        }
    }//GEN-LAST:event_jBlistarActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        // TODO add your handling code here:
       // Pede o ID em vez do nome
    String inputBusca = JOptionPane.showInputDialog(this, "Digite o ID da especialidade para buscar:");

    if (inputBusca != null && !inputBusca.trim().isEmpty()) {
        try {
            // Converte o texto digitado para número inteiro (int)
            int idBusca = Integer.parseInt(inputBusca.trim());

            EspecialidadeDAO dao = new EspecialidadeDAO();
            // Chama o método buscando por ID
            Especialidade esp = dao.buscarEspecialidade(idBusca); // Ou uma lista, caso prefira

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setNumRows(0); // Limpa a tabela

            if (esp != null) {
                // Adiciona a especialidade encontrada na tabela
                model.addRow(new Object[]{
                    esp.getId_especialidade(),
                    esp.getNome(),
                    esp.getDescricao()
                });
            } else {
                JOptionPane.showMessageDialog(this, "Nenhuma especialidade encontrada com este ID.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, digite um número válido para o ID.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro na busca: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jBbuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBlistar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
