/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.mycompany.appsistemahospitalar.GUI;

import com.mycompany.appsistemahospitalar.entities.Especialidade;

/**
 *
 * @author arthu
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setTitle("Sistema Hospitalar");
        setSize(1200,700);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        sairMenuItem1 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        medicoCadastro = new javax.swing.JMenuItem();
        pacienteCadastro = new javax.swing.JMenuItem();
        agendamentoCadastro = new javax.swing.JMenuItem();
        especialidade = new javax.swing.JMenuItem();
        helpMenu1 = new javax.swing.JMenu();
        medicoConsultaMenuItem = new javax.swing.JMenuItem();
        pacienteConsultaMenuItem1 = new javax.swing.JMenuItem();
        agendamentoConsultaMenuItem1 = new javax.swing.JMenuItem();
        atualizarMenu = new javax.swing.JMenu();
        medicoAtualizarMenu = new javax.swing.JMenuItem();
        pacienteAtualizarMenuItem = new javax.swing.JMenuItem();
        agendamentoAtualizarMenu = new javax.swing.JMenuItem();
        especialidadeAtualizarMenu = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Arquivo");

        sairMenuItem1.setMnemonic('d');
        sairMenuItem1.setText("Sair");
        sairMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(sairMenuItem1);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Cadastro");

        medicoCadastro.setMnemonic('d');
        medicoCadastro.setText("Medico");
        medicoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoCadastroActionPerformed(evt);
            }
        });
        editMenu.add(medicoCadastro);

        pacienteCadastro.setMnemonic('d');
        pacienteCadastro.setText("Paciente");
        pacienteCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteCadastroActionPerformed(evt);
            }
        });
        editMenu.add(pacienteCadastro);

        agendamentoCadastro.setMnemonic('d');
        agendamentoCadastro.setText("Agendamento");
        agendamentoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendamentoCadastroActionPerformed(evt);
            }
        });
        editMenu.add(agendamentoCadastro);

        especialidade.setMnemonic('d');
        especialidade.setText("Especialidade");
        especialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadeActionPerformed(evt);
            }
        });
        editMenu.add(especialidade);

        menuBar.add(editMenu);

        helpMenu1.setMnemonic('h');
        helpMenu1.setText("Consulta");

        medicoConsultaMenuItem.setMnemonic('d');
        medicoConsultaMenuItem.setText("Medico");
        medicoConsultaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoConsultaMenuItemActionPerformed(evt);
            }
        });
        helpMenu1.add(medicoConsultaMenuItem);

        pacienteConsultaMenuItem1.setMnemonic('d');
        pacienteConsultaMenuItem1.setText("Paciente");
        pacienteConsultaMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteConsultaMenuItem1ActionPerformed(evt);
            }
        });
        helpMenu1.add(pacienteConsultaMenuItem1);

        agendamentoConsultaMenuItem1.setMnemonic('d');
        agendamentoConsultaMenuItem1.setText("Agendamento");
        agendamentoConsultaMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendamentoConsultaMenuItem1ActionPerformed(evt);
            }
        });
        helpMenu1.add(agendamentoConsultaMenuItem1);

        menuBar.add(helpMenu1);

        atualizarMenu.setMnemonic('h');
        atualizarMenu.setText("Atualizar");

        medicoAtualizarMenu.setMnemonic('d');
        medicoAtualizarMenu.setText("Medico");
        medicoAtualizarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoAtualizarMenuActionPerformed(evt);
            }
        });
        atualizarMenu.add(medicoAtualizarMenu);

        pacienteAtualizarMenuItem.setMnemonic('d');
        pacienteAtualizarMenuItem.setText("Paciente");
        pacienteAtualizarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteAtualizarMenuItemActionPerformed(evt);
            }
        });
        atualizarMenu.add(pacienteAtualizarMenuItem);

        agendamentoAtualizarMenu.setMnemonic('d');
        agendamentoAtualizarMenu.setText("Agendamento");
        agendamentoAtualizarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendamentoAtualizarMenuActionPerformed(evt);
            }
        });
        atualizarMenu.add(agendamentoAtualizarMenu);

        especialidadeAtualizarMenu.setMnemonic('d');
        especialidadeAtualizarMenu.setText("Especialidade");
        especialidadeAtualizarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadeAtualizarMenuActionPerformed(evt);
            }
        });
        atualizarMenu.add(especialidadeAtualizarMenu);

        menuBar.add(atualizarMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medicoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoCadastroActionPerformed
        CadastroMedico form = new CadastroMedico();
        
        desktopPane.add(form);
        form.setVisible(true);
    }//GEN-LAST:event_medicoCadastroActionPerformed

    private void sairMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sairMenuItem1ActionPerformed

    private void pacienteCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteCadastroActionPerformed
<<<<<<< HEAD


=======
>>>>>>> ac8ee622604217ae42f64be62274a288ddd0c0aa
        CadastroPaciente form = new CadastroPaciente();
        
        desktopPane.add(form);
        form.setVisible(true);

    }//GEN-LAST:event_pacienteCadastroActionPerformed

    private void agendamentoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendamentoCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agendamentoCadastroActionPerformed

    private void medicoConsultaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoConsultaMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicoConsultaMenuItemActionPerformed

    private void pacienteConsultaMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteConsultaMenuItem1ActionPerformed
        
    }//GEN-LAST:event_pacienteConsultaMenuItem1ActionPerformed

    private void agendamentoConsultaMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendamentoConsultaMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agendamentoConsultaMenuItem1ActionPerformed

    private void especialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadeActionPerformed
        CadastroEspecialidade form = new CadastroEspecialidade();
        desktopPane.add(form);
        form.setVisible(true);
        
    }//GEN-LAST:event_especialidadeActionPerformed

    private void medicoAtualizarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoAtualizarMenuActionPerformed
        MedicoAtualizar form = new MedicoAtualizar();
        desktopPane.add(form);
        form.setVisible(true);
    }//GEN-LAST:event_medicoAtualizarMenuActionPerformed

    private void pacienteAtualizarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteAtualizarMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacienteAtualizarMenuItemActionPerformed

    private void agendamentoAtualizarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendamentoAtualizarMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agendamentoAtualizarMenuActionPerformed

    private void especialidadeAtualizarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadeAtualizarMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadeAtualizarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agendamentoAtualizarMenu;
    private javax.swing.JMenuItem agendamentoCadastro;
    private javax.swing.JMenuItem agendamentoConsultaMenuItem1;
    private javax.swing.JMenu atualizarMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem especialidade;
    private javax.swing.JMenuItem especialidadeAtualizarMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem medicoAtualizarMenu;
    private javax.swing.JMenuItem medicoCadastro;
    private javax.swing.JMenuItem medicoConsultaMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pacienteAtualizarMenuItem;
    private javax.swing.JMenuItem pacienteCadastro;
    private javax.swing.JMenuItem pacienteConsultaMenuItem1;
    private javax.swing.JMenuItem sairMenuItem1;
    // End of variables declaration//GEN-END:variables

}
