/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.mycompany.appsistemahospitalar.GUI;

/**
 *
 * @author arthu
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setTitle("Sistema Hospitalar");
        setSize(1200,700);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        sairMenuItem1 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        medicoMenuItem = new javax.swing.JMenuItem();
        pacienteMenuItem = new javax.swing.JMenuItem();
        agendamentoMenuItem = new javax.swing.JMenuItem();
        especialidade = new javax.swing.JMenu();
        medicoConsultaMenuItem = new javax.swing.JMenuItem();
        pacienteConsultaMenuItem1 = new javax.swing.JMenuItem();
        agendamentoConsultaMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Arquivo");

        sairMenuItem1.setMnemonic('d');
        sairMenuItem1.setText("Sair");
        sairMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(sairMenuItem1);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Cadastro");

        medicoMenuItem.setMnemonic('d');
        medicoMenuItem.setText("Medico");
        medicoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(medicoMenuItem);

        pacienteMenuItem.setMnemonic('d');
        pacienteMenuItem.setText("Paciente");
        pacienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(pacienteMenuItem);

        agendamentoMenuItem.setMnemonic('d');
        agendamentoMenuItem.setText("Agendamento");
        agendamentoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendamentoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(agendamentoMenuItem);

        menuBar.add(editMenu);

        especialidade.setMnemonic('h');
        especialidade.setText("Consulta");
        especialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadeConsultaMenuItem1ActionPerformed(evt);
            }
        });

        medicoConsultaMenuItem.setMnemonic('d');
        medicoConsultaMenuItem.setText("Medico");
        medicoConsultaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoConsultaMenuItemActionPerformed(evt);
            }
        });
        especialidade.add(medicoConsultaMenuItem);

        pacienteConsultaMenuItem1.setMnemonic('d');
        pacienteConsultaMenuItem1.setText("Paciente");
        pacienteConsultaMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteConsultaMenuItem1ActionPerformed(evt);
            }
        });
        especialidade.add(pacienteConsultaMenuItem1);

        agendamentoConsultaMenuItem1.setMnemonic('d');
        agendamentoConsultaMenuItem1.setText("Agendamento");
        agendamentoConsultaMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendamentoConsultaMenuItem1ActionPerformed(evt);
            }
        });
        especialidade.add(agendamentoConsultaMenuItem1);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Especialidade");
        especialidade.add(jCheckBoxMenuItem1);

        menuBar.add(especialidade);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medicoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicoMenuItemActionPerformed

    private void sairMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sairMenuItem1ActionPerformed

    private void pacienteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacienteMenuItemActionPerformed

    private void agendamentoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendamentoMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agendamentoMenuItemActionPerformed

    private void medicoConsultaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoConsultaMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicoConsultaMenuItemActionPerformed

    private void pacienteConsultaMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteConsultaMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacienteConsultaMenuItem1ActionPerformed

    private void agendamentoConsultaMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendamentoConsultaMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agendamentoConsultaMenuItem1ActionPerformed

    private void especialidadeConsultaMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadeConsultaMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadeConsultaMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agendamentoConsultaMenuItem1;
    private javax.swing.JMenuItem agendamentoMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu especialidade;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuItem medicoConsultaMenuItem;
    private javax.swing.JMenuItem medicoMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pacienteConsultaMenuItem1;
    private javax.swing.JMenuItem pacienteMenuItem;
    private javax.swing.JMenuItem sairMenuItem1;
    // End of variables declaration//GEN-END:variables

}
